
package GUI;

import Logica.Jugador;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.HeadlessException;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    JFMainOthello data = new JFMainOthello();

    /**
     * Crea nuevo formulario de Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenTablero = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlPanelPrincipal = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblImagenOthello = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnUnJugador = new javax.swing.JButton();
        btnDosJugadores = new javax.swing.JButton();
        jBAyuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblImagenTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/.I. 1.png"))); // NOI18N
        lblImagenTablero.setText("jLabel2");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPanelPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        pnlPanelPrincipal.setForeground(new java.awt.Color(204, 255, 255));
        pnlPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenida.setText("¡Bienvenido a Othello!");
        pnlPanelPrincipal.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        btnSalir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 120, 30));

        lblImagenOthello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla (2).png"))); // NOI18N
        pnlPanelPrincipal.add(lblImagenOthello, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 380, 270));

        btnLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnLogin.setText("Registrarse");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 30));

        btnUnJugador.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnUnJugador.setText("1P vs CPU");
        btnUnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnJugadorActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnUnJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, -1));

        btnDosJugadores.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnDosJugadores.setText("1P vs 2P");
        btnDosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosJugadoresActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnDosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 120, -1));

        jBAyuda.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jBAyuda.setText("Ayuda");
        jBAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAyudaActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(jBAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 30));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sergio Segura Menjívar");
        pnlPanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * método que contiene el botón de salir 
     * @param evt evento
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    /**
     * método que almacena el nombre del primer jugador
     */
    public String nombre = "";
    
    /**
     * método que contiene el botón de registrar
     * @param evt evento
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Jugador jugador = new Jugador(); //NO BORRAR!

        System.out.println("Entra al login");
        try {
            nombre = JOptionPane.showInputDialog("Escriba su nombre");
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite un texto válido");
            } else {
                jugador.setNombre(nombre);
                data.listaJugadores.add(jugador);
                System.out.println("tamano lista " + data.listaJugadores.size());
                for (int i = 0; i < data.listaJugadores.size(); i++) {
                    System.out.println("Y tiene los elementos: " + data.listaJugadores.get(i).getNombre());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos para registrar");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * método que contiene el botón de un jugador
     * @param evt evento
     */
    private void btnUnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnJugadorActionPerformed

        try {
            if (data.listaJugadores.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La lista esta vacia, por favor registrese");
            } else {
                String name = JOptionPane.showInputDialog("Escriba su nombre");
                if (name.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Digite un texto válido");
                } else {
                    for (int i = 0; i < data.listaJugadores.size() + 1; i++) {
                        if (data.listaJugadores.get(i).getNombre().equals(name)) {

                            System.out.println("Accediendo...");
                            JFMainOthello panel = new JFMainOthello();

                            panel.setVisible(true);
                            panel.lblJugadorUno.setText(name);
                            panel.lblJugadorDos.setText("");
                            panel.lblPiezasBlancas.setText("");
                            this.setVisible(false);
                        }
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUnJugadorActionPerformed
    
    /**
     * método que almacena el nombre del segundo jugador
     */
    public String nombre2;
    
    /**
     * método que contiene el botón de dos jugadores
     * @param evt evento
     */
    private void btnDosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosJugadoresActionPerformed
        String aux = "";
        try {
            if (data.listaJugadores.isEmpty() || data.listaJugadores.size() < 2) {
                JOptionPane.showMessageDialog(null, "No hay jugadores suficientes para acceder a este modo");
            } else {
                String nombre1 = JOptionPane.showInputDialog("Escriba el nombre del primer jugador");
                if (nombre1.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Elementos vacios, digite texto");
                } else {
                    for (int i = 0; i < data.listaJugadores.size(); i++) {

                        System.out.println(data.listaJugadores.get(i).getNombre());
                        if (data.listaJugadores.get(i).getNombre().equals(nombre1)) {
                            nombre2 = JOptionPane.showInputDialog("Escriba el nombre del segundo jugador");
                            for (int j = 0; j < data.listaJugadores.size(); j++) {
                                if (data.listaJugadores.get(j).getNombre().equals(nombre2)) {
                                    JFMainOthello panel = new JFMainOthello();
                                    panel.setVisible(true);
                                    panel.lblJugadorUno.setText(nombre1);
                                    panel.lblJugadorDos.setText(nombre2);
                                    this.setVisible(false);
                                }
                            }
                        }
                    }
                }
            }
        } catch (HeadlessException headlessException) {
        }
    }//GEN-LAST:event_btnDosJugadoresActionPerformed

    /**
     * método que contiene el botón de ayuda en la partida
     * @param evt evento
     */
    private void jBAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAyudaActionPerformed

        Ayuda fichero = new Ayuda(this, true);
        fichero.setVisible(true);
    }//GEN-LAST:event_jBAyudaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    
    /**
     * variables con los botones que aparecen en la interfase
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosJugadores;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnJugador;
    private javax.swing.JButton jBAyuda;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblImagenOthello;
    private javax.swing.JLabel lblImagenTablero;
    private javax.swing.JPanel pnlPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
